[server]
port = 8906
[server.log]
port = 8910 # 实时日志的端口

[db]
host = 'mongodb://localhost/wormhole'

[site.other1]
host = 'http://other1.xxx.com' # todo 自行加入其它配置，如外接其它服务器
apikey = 'apikey'

[jwt]
issuer = 'o'
sign = 'andromeda'
expMinute = 10

[[gatewayList]]
  url = '/andromeda'
  [gatewayList.option]
  target = 'http://127.0.0.1:60002/'
  changeOrigin = true
  ws = true
  [[gatewayList.rewriteList]]
    k = '^/andromeda'
    v = 'andromeda'
[[gatewayList]]
  url = '/xxx'
  [gatewayList.option]
  target = 'http://127.0.0.1:60001/'
  changeOrigin = true
  ws = true
  [[gatewayList.rewriteList]]
    k = '^/xxx'
    v = ''