server:
  port: 8906
  log:
    port: 8910

db:
  host: 'mongodb://localhost/wormhole'

site:
  other1: 
    host: 'http://other1.projectname.com'
    apikey: 'apikey'

jwt:
  issuer: 'o'
  sign: 'andromeda'
  expMinute: 10

gatewayList:
  - url: '/andromeda'
    option: 
      target: 'http://andromeda:8906/'
      changeOrigin: true
      ws: true
    rewriteList:
      - k: '^/andromeda'
        v: 'andromeda'
  - url: '/home'
    option: 
      target: 'http://contentcensor-home:8906'
      changeOrigin: true
      ws: true
    rewriteList:
      - k: '^/home'
        v: 'home'