server:
  port: 8906
  log:
    port: 8910

db:
  host: 'mongodb://localhost/wormhole'

site:
  other1: 
    host: 'http://other1.projectname.com'
    apikey: 'apikey'

jwt:
  issuer: 'o'
  sign: 'andromeda'
  expMinute: 10

gatewayList:
  - url: '/mlikyway'
    option: 
      target: 'http://127.0.0.1:60001/'
      changeOrigin: true
      ws: true
    rewriteList:
      - k: '^/mlikyway'
        v: 'mlikyway'
  - url: '/andromeda'
    option: 
      target: 'http://127.0.0.1:60002/'
      changeOrigin: true
      ws: true
    rewriteList:
      - k: '^/andromeda'
        v: 'andromeda'